apps/admin_app/lib/admin_app_web/router.ex
defmodule AdminAppWeb.Router do
  use AdminAppWeb, :router
  use Sentry.Plug
  import Snitch.Core.Tools.MultiTenancy.Repo, only: [get_prefix: 0]

  @secret_key_base Application.get_env(:admin_app, AdminAppWeb.Endpoint)[:secret_key_base]

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, @secret_key_base, "#{get_prefix()}_#{current_user.id}")
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  # This pipeline is just to avoid CSRF token.
  # TODO: This needs to be remove when the token issue gets fixed in custom form
  pipeline :avoid_csrf do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :authentication do
    plug(AdminAppWeb.AuthenticationPipe)
    plug(Auth.CurrentUser)
    plug(:put_user_token)
  end

  scope "/", AdminAppWeb do
    # Use the default browser stack
    pipe_through([:browser, :authentication])

    get("/", PageController, :index)

    get("/products/export_products", ProductController, :export_product)
    get("/fetch_states/:country_id", StockLocationController, :fetch_country_states)
    get("/orders/export_orders", OrderController, :export_order)
    get("/orders", OrderController, :index)
    get("/orders/:number/detail", OrderController, :show)
    put("/orders/:id/packages/", OrderController, :update_package, as: :order_package)
    put("/orders/:id/state", OrderController, :update_state, as: :order_state)
    put("/orders/:id/cod-payment", OrderController, :cod_payment_update, as: :order_cod_update)

    resources "/orders", OrderController, only: ~w[show create]a, param: "number" do
      get("/cart", OrderController, :get, as: :cart)
      post("/cart", OrderController, :remove_item, as: :cart)
      post("/cart/edit", OrderController, :edit, as: :cart)
      put("/cart/update", OrderController, :update_line_item, as: :cart)
      put("/cart", OrderController, :add, as: :cart)
      get("/address/search", OrderController, :address_search, as: :cart)
      put("/address/search", OrderController, :address_attach, as: :cart)
      get("/address/add", OrderController, :address_add_index, as: :cart)
      post("/address/add", OrderController, :address_add, as: :cart)
    end

    resources("/tax_categories", TaxCategoryController, only: [:index, :new, :create])
    resources("/stock_locations", StockLocationController)
    resources("/option_types", OptionTypeController)
    resources("/properties", PropertyController, except: [:show])
    resources("/registrations", RegistrationController, only: [:new, :create])
    resources("/session", SessionController, only: [:delete])
    resources("/users", UserController)
    resources("/roles", RoleController)
    resources("/permissions", PermissionController)
    resources("/variation_themes", VariationThemeController, except: [:show])
    resources("/prototypes", PrototypeController, except: [:show])
    resources("/products", ProductController)
    resources("/product_brands", ProductBrandController)
    resources("/payment_methods", PaymentMethodController)
    resources("/zones", ZoneController, only: [:index, :new, :create, :edit, :update, :delete])
    resources("/general_settings", GeneralSettingsController, except: [:delete])
    post("/payment-provider-inputs", PaymentMethodController, :payment_preferences)
    get("/product/category", ProductController, :select_category)
    post("/product-images/:product_id", ProductController, :add_images)
    post("/set-default-image/:product_id", ProductController, :update_default_image)
    delete("/product-images/", ProductController, :delete_image)

    get("/taxonomy", TaxonomyController, :show_default_taxonomy)
    resources("/taxonomy", TaxonomyController, only: [:create])

    get("/products/:product_id/property", ProductController, :index_property)
    get("/products/:product_id/property/new", ProductController, :new_property)
    get("/products/:product_id/property/:property_id/edit", ProductController, :edit_property)
    post("/products/:product_id/property/create", ProductController, :create_property)

    patch(
      "/products/:product_id/inventory_tracking",
      ProductController,
      :update_inventory_tracking
    )

    get("/dashboard", DashboardController, :index)

    post(
      "/products/:product_id/property/:property_id/update",
      ProductController,
      :update_property
    )

    delete(
      "/products/:product_id/property/:property_id/delete",
      ProductController,
      :delete_property
    )

    delete("/variant_delete/:id", ProductController, :delete_variant)

    get("/shipping-policy/new", ShippingPolicyController, :new)
    get("/shipping-policy/:id/edit", ShippingPolicyController, :edit)
    put("/shipping-policy/:id", ShippingPolicyController, :update)
    get("/product/import/etsy", ProductImportController, :import_etsy)
    get("/product/import/etsy/callback", ProductImportController, :oauth_callback)
    get("/product/import/etsy/progress", ProductImportController, :import_progress)

    ### tax
    get("/tax", Tax.TaxConfigController, :index)
    put("/tax/:id", Tax.TaxConfigController, :update)
    get("/tax/tax-classes", Tax.TaxClassController, :index)
    get("/tax/tax-classes/new", Tax.TaxClassController, :new)
    get("/tax/tax-classes/:id/edit", Tax.TaxClassController, :edit)
    post("/tax/tax-classes/new", Tax.TaxClassController, :create)
    put("/tax/tax-classes/:id", Tax.TaxClassController, :update)
    delete("/tax/tax-classes/:id", Tax.TaxClassController, :delete)

    resources("/tax/tax-zones", Tax.TaxZoneController, except: [:show]) do
      resources("/tax-rates", Tax.TaxRateController, except: [:show])
    end
  end

  scope "api/", AdminAppWeb do
    ### promotions

    resources("/promotions", PromotionController, except: [:show, :new])
    get("/promo-rules", PromotionController, :rules, as: :promo_rules)
    get("/promo-actions", PromotionController, :actions, as: :promo_actions)
    get("/promo-calculators", PromotionController, :calculators, as: :promo_calc)
    post("/promo-rule-prefs", PromotionController, :rule_preferences, as: :promo_rule_prefs)
    post("/promo-action-prefs", PromotionController, :action_preferences, as: :promo_action_prefs)
    post("/promo-calc-prefs", PromotionController, :calc_preferences, as: :promo_calc_prefs)
    put("/promo/:id/archive", PromotionController, :archive)
  end

  scope "/", AdminAppWeb do
    pipe_through(:avoid_csrf)
    patch("/variant_state/:id", ProductController, :toggle_variant_state)
    post("/products/variants/new", ProductController, :new_variant)
  end

  scope "/", AdminAppWeb do
    pipe_through(:browser)
    get("/orders/:number/show-invoice", OrderController, :show_invoice)
    get("/orders/:number/show-packing-slip", OrderController, :show_packing_slip)
    get("/orders/:number/download-packing-slip", OrderController, :download_packing_slip_pdf)
    get("/orders/:number/download-invoice", OrderController, :download_invoice_pdf)
    resources("/session", SessionController, only: [:new, :create, :edit, :update])
    get("/password_reset", SessionController, :password_reset)
    get("/password_recovery", SessionController, :verify)
    post("/check_email", SessionController, :check_email)
  end

  # Other scopes may use custom stacks.
  scope "/api", AdminAppWeb do
    pipe_through(:api)

    resources("/stock_locations", StockLocationController)
  end

  scope "/api", AdminAppWeb.TemplateApi do
    pipe_through(:api)

    resources("/option_types", OptionTypeController)
    get("/categories/:taxon_id", TaxonomyController, :index)
    get("/taxon/:taxon_id", TaxonomyController, :taxon_edit)
    delete("/taxon/:taxon_id", TaxonomyController, :taxon_delete)
    get("/taxon/:taxon_id/aggregate", TaxonomyController, :taxon_delete_aggregate)
    put("/taxonomy/update", TaxonomyController, :update_taxon)
    post("/product_option_values/:id", OptionTypeController, :update)
  end

  scope "/api", AdminAppWeb.Api do
    pipe_through(:api)

    post("/stock", StockController, :get_stock)
    post("/stock_update", StockController, :update_stock)
  end

  scope "/", AdminAppWeb do
    pipe_through([:browser, :authentication])

    # Don't add phoenix routes after this route as, all routes that does not match
    # Phoenix routes goes to react app.
    get("/*path", ReactController, :index)
  end
end

apps/admin_app/lib/admin_app/order/package.ex
defmodule AdminApp.PackageContext do
  import Ecto.Query
  alias Snitch.Data.Schema.Package
  alias Snitch.Core.Tools.MultiTenancy.Repo

  def update_packages(state, order_id) do
    query =
      from(
        package in Package,
        where: package.order_id == ^order_id
      )

    case Repo.update_all(query, set: [state: state]) do
      {0, _} ->
        {:error, "Update failed"}

      _ ->
        {:ok, "updated"}
    end
  end
end

apps/admin_app/lib/admin_app_web/views/order_view.ex
defmodule AdminAppWeb.OrderView do
  use AdminAppWeb, :view
  import Phoenix.HTML.Tag
  alias Snitch.Data.Model.{Country, State, User}
  alias Snitch.Domain.Order, as: OrderDomain
  alias AdminAppWeb.Helpers
  alias SnitchPayments.PaymentMethodCode

  @bootstrap_contextual_class %{
    "slug" => "light",
    "cart" => "light",
    "address" => "light",
    "payment" => "light",
    "processing" => "warning",
    "shipping" => "warning",
    "shipped" => "info",
    "cancelled" => "secondary",
    "completed" => "success"
  }

  def order_user_name(order) do
    case User.get_username(order.user) do
      nil ->
        "N.A."

      name ->
        name
    end
  end

  def get_params(params) do
    content_tag :div, class: "pagination-params", data: Map.to_list(params) do
    end
  end

  def order_item_count(order) do
    case length(order.line_items) do
      1 ->
        "1 item"

      items ->
        Integer.to_string(items) <> " items"
    end
  end

  def format_date(date) do
    Helpers.format_date(date)
  end

  def get_country_state(order) do
    country = get_country(order.shipping_address.country_id)
    state = get_state(order.shipping_address.state_id)
    state.name <> ", " <> country.name
  end

  def colorize(%{state: state}) do
    "table-" <> Map.fetch!(@bootstrap_contextual_class, state)
  end

  def state_badge(state) do
    color_class = @bootstrap_contextual_class[state]
    content_tag(:span, state, class: "badge badge-pill badge-#{color_class}")
  end

  defp render_line_item(line_item, order) do
    content = [
      render_variant(line_item.product),
      content_tag(:td, line_item.unit_price),
      render_quantity_with_stock(line_item)
    ]

    content_tag(:tr, List.flatten(content))
  end

  def render_variant(product) do
    content_tag(:td, product.sku)
  end

  def render_variant_name(product) do
    content_tag(:td, product.name)
  end

  def line_item_total(line_item) do
    Money.mult!(line_item.unit_price, line_item.quantity)
  end

  def order_items_total(order) do
    order
    |> OrderDomain.total_amount()
    |> Money.to_string!()
  end

  def tax_total(order) do
    order.packages
    |> OrderDomain.total_tax()
    |> Money.to_string!()
  end

  def shipping_total(order) do
    order.packages
    |> OrderDomain.shipping_total()
    |> Money.to_string!()
  end

  def shipping_method(order) do
    package = List.first(order.packages)
    String.capitalize(package.shipping_method.name)
  end

  defp render_update_buttons(item, order) do
    if is_editable?(order.state) do
      content_tag(
        :td,
        form_tag "/orders/#{order.number}/cart/edit?update=#{item}", method: "post" do
          content_tag(:button, ["update"], class: "btn btn-primary", type: "submit")
        end
      )
    end
  end

  defp render_buttons(item, order) do
    if is_editable?(order.state) do
      content_tag(
        :td,
        form_tag "/orders/#{order.number}/cart?edit=#{item}", method: "post" do
          content_tag(:button, ["remove"], class: "btn btn-primary", type: "submit")
        end
      )
    end
  end

  def render_quantity_with_stock(line_item) do
    content_tag(:td, "#{line_item.quantity}")
  end

  def render_address(nil) do
    content_tag(:div, ["N.A"])
  end

  def render_address(address) do
    content_tag(:div, [
      content_tag(:div, ["#{address.first_name} #{address.last_name}"], class: "name"),
      content_tag(
        :div,
        [
          address.address_line_1,
          address.address_line_2,
          address.city,
          address.phone,
          address.zip_code
        ]
        |> Enum.reject(&(&1 == nil))
        |> Enum.intersperse([",", tag(:br)])
        |> List.flatten(),
        class: "addres-detail"
      )
    ])
  end

  defp is_editable?(_), do: true

  defp render_search_item(item, order) do
    content = [
      content_tag(:td, item.sku),
      content_tag(:td, item.selling_price),
      content_tag(:td, tag(:input, name: "quantity", id: "quantity")),
      content_tag(:td, content_tag(:button, ["Add"], type: "submit"))
    ]

    list =
      form_tag "/orders/#{order.number}/cart?add=#{item.id}", method: "put" do
        List.flatten(content)
      end

    content_tag(:tr, list)
  end

  def render_update_item(item, order) do
    content = [
      content_tag(:td, item.product.sku),
      content_tag(:td, item.product.selling_price),
      content_tag(:td, tag(:input, name: "quantity", value: item.quantity)),
      content_tag(:td, tag(:hidden, name: "product_id", value: item.product_id)),
      content_tag(:td, content_tag(:button, ["Add"], type: "submit"))
    ]

    list =
      form_tag "/orders/#{order.number}/cart/update?update=#{item.id}", method: "put" do
        List.flatten(content)
      end

    content_tag(:tr, list)
  end

  def build_address(address, order) do
    content = [
      content_tag(:td, address.first_name),
      content_tag(:td, address.last_name),
      content_tag(:td, address.address_line_1),
      content_tag(:td, address.phone),
      content_tag(:td, address.city),
      content_tag(
        :td,
        content_tag(:button, ["Attach"], type: "submit", class: "btn btn-sm btn-primary")
      )
    ]

    list =
      form_tag "/orders/#{order.number}/address/search?address_id=#{address.id}", method: "put" do
        List.flatten(content)
      end

    content_tag(:tr, list)
  end

  def display_email(order) do
    if order.user do
      order.user.email
    else
      "Guest Order"
    end
  end

  def check_for_cod(order) do
    Enum.any?(order.payments, fn payment ->
      payment.payment_type == PaymentMethodCode.cash_on_delivery()
    end)
  end

  def cod_status(order) do
    cod_payment =
      Enum.find(order.payments, fn payment ->
        payment.payment_type == PaymentMethodCode.cash_on_delivery()
      end)

    case cod_payment.state do
      "paid" ->
        %{display: "Mark as Unpaid", state: "pending"}

      _ ->
        %{display: "Mark as Paid", state: "paid"}
    end
  end

  defp render_invoice_line_item(line_item, order) do
    content = [
      render_variant_name(line_item.product),
      render_quantity(line_item),
      content_tag(:td, " #{line_item.unit_price} ")
    ]

    content_tag(:tr, List.flatten(content))
  end

  defp render_quantity(line_item) do
    content_tag(:td, " x #{line_item.quantity}")
  end

  def get_country(country_id) do
    country_id |> Country.get() |> get_response
  end

  def get_state(state_id) do
    state_id |> State.get() |> get_response
  end

  defp get_response({:ok, struct}) do
    struct
  end

  defp get_state_name(state_id) do
    state_id |> get_state() |> Map.get(:name)
  end

  defp get_iso(country_id) do
    country_id |> get_country() |> Map.get(:iso)
  end

  def order_total(order) do
    {:ok, total} = Money.to_string(OrderDomain.total_amount(order))
    total
  end

  def get_support_url() do
    Application.get_env(:admin_app, AdminAppWeb.Endpoint)[:support_url]
  end

  def get_support_email() do
    Application.get_env(:admin_app, AdminAppWeb.Endpoint)[:sendgrid_sender_mail]
  end

  def get_docs_url() do
    Application.get_env(:admin_app, AdminAppWeb.Endpoint)[:docs_url]
  end

  def get_payment_name(payment) do
    payment.payment_method.name
  end
end

apps/admin_app/lib/admin_app_web/templates/order/index.html.eex
<div class="list-container">
   <div class="row m-0 list-header">
      <div class="col-10 p-0">
         <h2>Orders & Shipping</h2>
      </div>
   </div>
   <div class="row m-0">
      <div class="col-9 p-0">
         <nav class="navbar navbar-expand-sm">
            <ul class="nav nav-tabs">
               <li class="order-tab nav-item"><%= link "Pending", to: order_path(@conn, :index, %{"category" => "pending"}),
                  class: "nav-link active" %></li>
               <li class="order-tab nav-item"><%= link "Unshipped", to: order_path(@conn, :index,
                  %{"category" => "unshipped"}), class: "nav-link" %></li>
               <li class="order-tab nav-item"><%= link "Shipped", to: order_path(@conn, :index,
                  %{"category" => "shipped"}), class: "nav-link" %></li>
               <li class="order-tab nav-item"><%= link "Complete", to: order_path(@conn, :index,
                  %{"category" => "complete"}), class: "nav-link" %></li>
               <div class="input-group mb-3">
                  <input type="text" class="form-control" id="order_search_box" placeholder="Search by customer name, email or order number" aria-label="Recipient's username" aria-describedby="button-addon2">
                  <div class="input-group-append">
                     <button class="btn btn-outline-secondary" type="submit" id="order-search-button"><i class="fa fa-search"></i></button>
                  </div>
               </div>
               <form class="form-inline mb-3 float-sm-right">
                  <div class="form-group p-2">
                     <label for="from" class="col-form-label-sm pr-2">From : </label>
                     <input class="form-control form-control-sm" id="selected_start_date" value=<%= @start_date %> type="date" name="from">
                  </div>
                  <div class="form-group p-2">
                     <label for="to" class="col-form-label-sm pr-2">To : </label>
                     <input class="form-control form-control-sm" id="selected_end_date" value=<%= @end_date %> type="date" name="to">
                  </div>
               </form>
            </ul>
         </nav>
         <div class="row m-0 list orders-list">
            <div class="col-12 p-0">
               <%= render "order_listing.html", conn: @conn, orders: @orders, token: @token %>
            </div>   
         </div>
      </div>
      <div class="col-3 rightbar">
         <form>
            <div class="form-group">
               <label class="label-heading">Sort by</label>
               <select class="form-control selected-option">
                  <option value="null" selected disabled>-- Please select an option --</option>
                  <option value="desc">Newest</option>
                  <option value="asc">Oldest</option>
               </select>
            </div>
            <div class="col-sm-12 p-0">
               <label class="label-heading">Sort By Date</label>
               <div class="radio">
                  <label>
                  <input type="radio" name="o3" value="">
                  <span class="cr"><i class="cr-icon fa fa-circle"></i></span>
                  Option1
                  </label>
               </div>
               <div class="radio">
                  <label>
                  <input type="radio" name="o3" value="" checked>
                  <span class="cr"><i class="cr-icon fa fa-circle"></i></span>
                  Option2
                  </label>
               </div>
               <div class="dropdown col-4 p-0">
                  <a class="p-2 btn btn-secondary btn-outline-secondary dropdown-toggle options" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Export Orders
                  </a>
                  <div class="dropdown-menu dropdown-menu-right">
                    <%= link("CSV", to: order_path(@conn, :export_order, %{"format" => "csv"}), class: "dropdown-item")%>
                    <%= link("XLSX", to: order_path(@conn, :export_order, %{"format" => "xlsx"}), class: "dropdown-item")%>
                  </div>
               </div>
               </br>
               <div class="form-group">
                  <label class="label-heading">Filter by state</label>
                  <select class="form-control" id="selected_state">
                     <option value="null" selected disabled>-- Please select an order state --</option>
                     <option value="cart">Cart</option>
                     <option value="address">Address</option>
                     <option value="delivery">Delivery</option>
                     <option value="payment">Payment</option>
                     <option value="confirmed">Confirmed</option>
                     <option value="complete">Complete</option>
                     <option value="cancelled">Cancelled</option>
                  </select>
               </div>
            </div>
            </div>
         </form>
      </div>
   </div>
</div>

apps/admin_app/lib/admin_app_web/templates/order/line_item_card.html.eex
<div class="media mt-3 lineitem-detail">
   <a class="pr-3" href="#">
   <img src="/images/empty-img.png" alt="Default">
   </a>
   <div class="media-body">
      <div class="mt-0 text-capitalize name"><%= render_variant(@line_item.product) %></div>
      <div class="variant">
         <span>Quantity</span>
         <span><%= render_quantity_with_stock(@line_item) %></span>
      </div>
   </div>
</div>

apps/admin_app/lib/admin_app_web/templates/order/order_listing.html.eex
<%= if length(@orders.list) == 0 do %>
  <p>No Orders to Show</p>
<% else %>
  <%= render_many @orders.list, AdminAppWeb.OrderView, "order_list_card.html", conn: @conn, as: :order %>
  <div class="order-pagination">
    <%= pagination_links(@conn, @orders, &order_path/3) %>
    <hr>
    <%= pagination_text(@orders) %>
    <%= get_params(@conn.params) %>
  </div>
<% end %> 

apps/admin_app/lib/admin_app_web/templates/order/show.html.eex
<div class="list-container">
   <div class="pt-3 pb-0 pr-3 pl-3 back"> <img src="/images/left-arrow.svg"
      width="20" height="20" class="d-inline-block align-top" alt="">
      <a href="/orders">Orders </a>
   </div>
   <h4 class="p-3 m-0">Order Detail</h4>
   <div class="row m-0 order-detail lineitem">
      <div class="col-12">
        <div class="row">
            <div class="col-6">
               <h2>Order from <%= order_user_name(@order) %></h2>
               <div class="orderon"><span class="mr-2"><%= @order.number %></span> via Avia</div>
               <div class="orderon">
                <span class="mr-1"><%= order_item_count(@order) %>,</span>
                <span><%= @order_total %></span>
               </div>
            </div>
            <div class="col-6">
              <div class="row">
                <div class="col-7"></div>
                <div class="col-5">
                    <div class="orderhead">Ship Details</div>
                    <div class="orderon">Ordered <%= format_date(@order.updated_at) %></div>
                    <div class="orderon">Ship to <%= get_country_state(@order) %></div>
                </div>
              </div>
            </div>
         </div>
         <div class="my-3 order-btns">
            <div class="btn-group">
              <button class="btn btn-outline-secondary btn-md dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Order Actions
              </button>
              <div class="dropdown-menu">
                <%= link "Pending", to: order_package_path(@conn, :update_package,
                    @order.id, [state: :processing]), method: :put, class: "dropdown-item" %>
                <%= link "Ready", to: order_package_path(@conn, :update_package,
                    @order.id, [state: :ready]), method: :put, class: "dropdown-item" %>
                <%= link "Ship", to: order_package_path(@conn, :update_package,
                    @order.id, [state: :shipped]), method: :put, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= if check_for_cod(@order) do %>
                  <% cod_status = cod_status(@order)%>
                  <%= link cod_status.display, to: order_cod_update_path(@conn, :cod_payment_update,
                    @order.id, [state: cod_status.state]), method: :put, class: "dropdown-item" %>
                <% end %>
                 <%= link "Mark as Delivered", to: order_package_path(@conn, :update_package,
                    @order.id, [state: :delivered]), method: :put, class: "dropdown-item" %>
                <%= link "Mark as Complete", to: order_state_path(@conn, :update_state,
                    @order.id, [state: :complete]), method: :put, class: "dropdown-item" %>
                </div>
            </div>
         </div>
         <h3 class="mt-3">Print</h3>
         <div class="card col-12 print">
            <div class="print-sub-head">What would you like to print?</div>
            <div class="media lineitem-detail mx-3">
               <div class="media-body">
                  <a class="mt-0 text-capitalize name">Packing slips</a>
                  <div class="variant">
                    Print the packing slips for the order.
                  </div>
               </div>
               <a class="btn btn-primary float-right" style="width: 100px;" href="/orders/<%= @order.number %>/download-packing-slip" > Download </a>
            </div>
            <div class="media lineitem-detail mt-3 mx-3">
               <div class="media-body">
                  <a class="mt-0 text-capitalize name">Order Invoice</a>
                  <div class="variant">
                    Download the order invoice.
                  </div>
               </div>
               <a class="btn btn-primary float-right " style="width: 100px;" href="/orders/<%= @order.number %>/download-invoice"> Download</a>
            </div>
            <div class="media lineitem-detail mt-3 mx-3">
               <div class="media-body">
                  <a class="mt-0 text-capitalize name">Show Packing Slip</a>
                  <div class="variant">
                    Preview the packing slip.
                  </div>
               </div>
               <a class="btn btn-primary float-right " style="width: 100px;" href="/orders/<%= @order.number %>/show-packing-slip">Show</a>
            </div>
         </div>
         <h3 class="mt-3">Shipping Details</h3>
         <div class="card col-12">
            <div class="row">
               <div class="col-4">
                  <div class="address">
                     <div class="ship mb-3"> Ship to </div>
                     <%= render_address(@order.shipping_address) %>
                  </div>
               </div>
               <div class="col-8">
                  <div class="address">
                     <div class="ship mb-3"> Shipping Method Selected </div>
                     <div class="std-shipping">
                        <div class="float-left">
                          <%= shipping_method(@order) %>
                        </div>
                        <div class="float-right ship ">
                          <%= @order_total %>
                        </div>
                        <div class="clearfix"></div>
                     </div>
                     <%= for line_item <- @order.line_items do %>
                     <div class="media mt-3 lineitem-detail">
                        <a class="pr-3" href="#">
                          <img src="/images/empty-img.png" alt="Default">
                        </a>
                        <div class="media-body">
                          <div class="mt-0 text-capitalize"><%= line_item.product.name %></div>
                        </div>
                        <div class="ship" >
                          Qty <span>1</span>
                        </div>
                     </div>
                     <% end %>
                  </div>
               </div>
            </div>
         </div>
         <h3 class="mt-3">Receipt # <%= @order.number %></h3>
         <div class="card col-12">
            <div class="table-responsive mt-2">
               <table class="table">
                  <thead>
                     <tr class="d-flex">
                        <th class="col-8">Items</th>
                        <th class="col-2 text-center">Quantity</th>
                        <th class="col-2 text-right">Item Price</th>
                     </tr>
                  </thead>
                  <tbody>
                    <%= for line_item <- @order.line_items do %>
                      <tr class="d-flex">
                          <td class="col-8 text-left">
                            <div class="media lineitem-detail">
                                <a class="pr-2 mr-1" href="#" >
                                <img href="#" src="/images/empty-img.png" alt="Default">
                                </a>
                                <div class="media-body">
                                  <a class="mt-0 text-capitalize name"> <%= line_item.product.name %></a>
                                  <div class="variant">
                                  </div>
                                </div>
                            </div>
                          </td>
                          <td class="col-2"><%= line_item.quantity %></td>
                          <td class="col-2 text-right"><%= line_item.unit_price %></td>
                      </tr>
                      <tr class="d-flex">
                      <td class="col-10 text-left" colspan="2">Item Total</td><td class="col-2 text-right"><%= line_item_total(line_item) %></td>
                      </tr>
                     <% end %>
                  </tbody>
               </table>
            </div>
            <div class="row m-0 summery-datail">
                  <div class="col-6 left">
                     Shipping cost
                  </div>
                  <div class="col-6 right">
                     <%= shipping_total(@order) %>
                  </div>
               </div>
               <div class="row m-0 total">
                  <div class="col-6 left">
                     <div>Tax</div>
                     <div class="total-text">Order total</div>
                  </div>
                  <div class="col-6 right">
                     <div> <%= tax_total(@order) %> </div>
                     <div class="total-text"> <%= @order_total %></div>
                     <div class="paid-via mt-4">
                      <%= for payment <- @order.payments do %>
                        <div class="">
                            Paid via <b> <%= get_payment_name(payment) %></b>
                        </div>
                        <div class="n-paid">
                           Status <%= payment.state %>
                        </div>
                        <% end %>
                     </div>
                  </div>
               </div>
         </div>
      </div>
</div>